Meeting20221103
geomapfish/geomapfish_website pull request #102
Opened 2022-12-28 10:46 UTC by maltaesousa

2023-01-10 13:24 UTC, rbovard requested changes
Looks good, thanks a lot.

Just a date typo to fix ;)

2023-01-10 13:24 UTC, rbovard commented on content/pages/98_meetings_de.md
> +* [Yverdon-les-Bains, 24.11.2022](meeting_minutes/2022-11-03)
Date issue?

2023-01-10 13:24 UTC, rbovard commented on content/pages/98_meetings_fr.md
> +* [Yverdon-les-Bains, 24.11.2022](meeting_minutes/2022-11-03)
Date issue?

2023-01-11 07:55 UTC, maltaesousa commented
@rbovard thanks for the review!

2023-01-11 07:55 UTC, merged