Add PSC+UG lists
geomapfish/geomapfish_website pull request #51
Opened 2018-11-23 12:26 UTC by rbovard

Fix https://github.com/geomapfish/geomapfish_website/issues/28#issuecomment-325677083

Please review.

If it's ok (content and style), I'll translate it in english but I'll need some help for the german version.

2018-11-23 12:50 UTC, kalbermattenm requested changes

2018-11-23 12:50 UTC, kalbermattenm commented on content/pages/1_community_fr.md
> +* ALPGIS SA
Not participating anymore  (only for information)

2018-11-23 12:50 UTC, kalbermattenm commented on content/pages/1_community_fr.md
> +* Canton de Thurgovie
Not participating (only for information)

2018-11-23 12:50 UTC, kalbermattenm commented on content/pages/1_community_fr.md
> +* Camptocamp (fournisseur)
```suggestion
* Camptocamp SA (fournisseur)
```

2018-11-23 12:51 UTC, kalbermattenm commented
Great ! Thanks a lot !

I'll post the german content in a few minutes.

2018-11-23 13:06 UTC, kalbermattenm commented
Here is the German part:

```
### PSC

Der PSC besteht aus den folgenden Entitäten:

* Basel-Landschaft, Basel-Stadt, Neuenburg (Kantone)
* Cartoriviera, Nyon (Städte)
* GeoCommunes (privat Unternehmen)
* Camptocamp (Anbieter)

### Benutzergruppe

Die Benutzergruppe besteht aus Vertreter von folgenden Entitäten:

* Kanton Basel-Landschaft
* Kanton Basel-Stadt
* Kanton Neuenburg
* Kanton Thurgau
* Kanton Waadt
* Kanton Graubünden
* Kanton Jura
* Kanton Tessin
* CartoJuraLéman
* Gemeinde Nendaz
* Ecole polytechnique fédérale de Lausanne
* Gemetris SA
* HKD Géomatique SA
* Ingéo SA
* Jaquier Pointet SA
* RUDAZ + PARTNER SA
* swisstopo
* Stadt Lausanne
* Stadt Morges
* Stadt Nyon
* Stadt Prilly
* Stadt Pully
* Stadt Vevey
* Stadt Yverdon-les-Bains
```

2018-11-23 15:36 UTC, rbovard commented
Thanks for your feedback and the german translation.

I'll add the english one on Monday (and also update pages metadata).

2018-11-23 15:45 UTC, kalbermattenm commented
Thanks for your work !

2018-11-27 15:06 UTC, rbovard commented
@kalbermattenm Please review.

2018-11-27 15:28 UTC, kalbermattenm approved these changes
Looks good to me.

Feel free to publish. Maybe it would be good to send a global email to the user group about these changes.

Thanks a lot !!

2018-11-28 07:31 UTC, merged