Minutes for 2019-11-11 meeting
geomapfish/geomapfish_website pull request #63
Opened 2019-11-18 13:25 UTC by kalbermattenm

@rbovard , could please review that ?

2019-11-19 14:55 UTC, rbovard requested changes
Thanks a lot for that @kalbermattenm !

I've added some details and flagged minor issues.

As usual, I didn't check german transaltion ;)

Question: don't you want to update the roadmap page (especially the dates for v2.5)?

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +URL: meeting_minutes2019-11-11
Missing `/`

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +###	GetItFixed (Camptocamp)
Extra spaces

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +###	PSC Koordination
Extra spaces

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +###	Version 2.6 : discussion selon priorisation usergroup
Extra spaces

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +###	Dockerisation et hébergement : vue d’ensemble et solutions (Camptocamp)
Extra spaces

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +###	GetItFixed (Camptocamp)
Extra spaces

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +Normalement, une nouvelle version 2.5 sera disponible autour de mars 2020
La version 2.5 sera disponible autour de mars 2020.

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +Le PSC se réunira d'ici quelques semaines pour définir que sont les fonctionnalités qui seront inclues dans la version 2.6.
pour définir les fonctionnalités qui seront incluses

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +Le coordinateur actuel va devoir arrêter cette tâche. Un-e remplaçant-e est activement recherché-e.
Après de nombreuses années de service, le coordinateur actuel va devoir arrêter cette tâche. Un grand merci à lui pour tout le travail effectué.

Un-e remplaçant-e est activement recherché-e, n'hésitez pas à contacter le PSC à ce sujet.

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +Merci à TOUS LES MEMBRES de compléter ce tableau.
à **TOUS LES MEMBRES** de

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +Normalerweise wird Version 2.5 im März 2020 zur Verfügung sein.
See review on FR version.

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +Wir bieten ALLE TEILNEHMER diese Tabelle zu vervollständigen.
See review on FR version.

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +Der aktuelle Koordinator kann leider nicht mehr mitmachen. Ein neuer Koordinator wird aktiv gesucht.
See review on FR version.

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_fr.md
> +
Démo: https://geomapfish-demo.camptocamp.com/getitfixed/getitfixed/issues

2019-11-19 14:55 UTC, rbovard commented on content/pages/meeting_minutes/2019-11-11_de.md
> +
Demo: https://geomapfish-demo.camptocamp.com/getitfixed/getitfixed/issues

2019-11-22 10:03 UTC, kalbermattenm commented
Thanks for your review @rbovard 

> Question: don't you want to update the roadmap page (especially the dates for v2.5)?

I thought that it was a bit to early to specify that. I would rather like to change this date once the new version 2.6 defined. (if you don't mind...)

Merging this PR

2019-11-22 10:03 UTC, kalbermattenm commented
And updating website...

2019-11-22 10:03 UTC, merged