Add master documentation link
geomapfish/geomapfish_website pull request #64
Opened 2020-02-12 12:01 UTC by ponceta

https://camptocamp.github.io/c2cgeoportal/master/

2020-02-12 12:04 UTC, rbovard requested changes
Thanks @ponceta 

Could you please also update FR and DE pages?

2020-02-12 12:24 UTC, ponceta commented
> Thanks @ponceta
> 
> Could you please also update FR and DE pages?

Yep! Si ça te vas comme ça?

2020-02-12 13:16 UTC, rbovard approved these changes

2020-02-12 13:17 UTC, rbovard requested changes
Thanks for your edits.

Just one typo in your last commits and we're good: ` : ` > `: `

2020-03-19 06:34 UTC, ponceta commented on content/pages/4_roadmap_de.md
> +* Dokumentation : laufend https://camptocamp.github.io/c2cgeoportal/master/
```suggestion
* Dokumentation : laufend (https://camptocamp.github.io/c2cgeoportal/master/)
```

2020-03-19 06:41 UTC, ponceta commented
> Thanks for your edits.
> 
> Just one typo in your last commits and we're good: `:` > `: `

@rbovard je vois pas où?

C'est peut-être plus simple si tu proposes directement la bonne variante avec l'outil de suggestion de changements? 

![image](https://user-images.githubusercontent.com/8614223/77038806-ed085f00-69b4-11ea-9a0a-07f58498a64b.png)

2020-03-19 06:57 UTC, rbovard requested changes
Done! (I didn't know this feature, thanks)

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap.md
> +* Documentation : to be released (https://camptocamp.github.io/c2cgeoportal/master/)
```suggestion
* Documentation: to be released (https://camptocamp.github.io/c2cgeoportal/master/)
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.4/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.4/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.3/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.3/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.2/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.2/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_de.md
> +* Dokumentation : laufend (https://camptocamp.github.io/c2cgeoportal/master/)
```suggestion
* Dokumentation: laufend (https://camptocamp.github.io/c2cgeoportal/master/)
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_de.md
> +* Dokumentation : https://camptocamp.github.io/c2cgeoportal/2.4/
```suggestion
* Dokumentation: https://camptocamp.github.io/c2cgeoportal/2.4/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_de.md
> +* Dokumentation : https://camptocamp.github.io/c2cgeoportal/2.3/
```suggestion
* Dokumentation: https://camptocamp.github.io/c2cgeoportal/2.3/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_de.md
> +* Dokumentation : https://camptocamp.github.io/c2cgeoportal/2.2/
```suggestion
* Dokumentation: https://camptocamp.github.io/c2cgeoportal/2.2/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_fr.md
> +* Documentation : En cours (https://camptocamp.github.io/c2cgeoportal/master/)
```suggestion
* Documentation: En cours (https://camptocamp.github.io/c2cgeoportal/master/)
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_fr.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.4/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.4/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_fr.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.3/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.3/
```

2020-03-19 06:57 UTC, rbovard commented on content/pages/4_roadmap_fr.md
> +* Documentation : https://camptocamp.github.io/c2cgeoportal/2.2/
```suggestion
* Documentation: https://camptocamp.github.io/c2cgeoportal/2.2/
```

2020-03-19 08:57 UTC, ponceta commented
> Done! (I didn't know this feature, thanks)

C'est vraiment cool, je découvre aussi, du coup tu peux ajouter toutes les suggestions au "batch" et faire un commit unique avec les corrections proposées.

2020-03-19 09:28 UTC, rbovard approved these changes

2020-03-19 09:29 UTC, merged