Add SEO & fix author tag
geomapfish/geomapfish_website pull request #91
Opened 2022-04-25 12:37 UTC by pfanguin

2022-04-25 12:40 UTC, pfanguin commented
@svareg @rbovard I added the keywords and description for all pages, If you want more keywords or change descriptions let me know ! 
Maybe the german must be corrected !

2022-05-04 10:39 UTC, rbovard requested changes
Thanks for the work!

Is there a way to see the result somewhere?

I noticed some typos when reviewing FR and EN versions.

@svareg Can you please check DE version?

2022-05-04 10:39 UTC, rbovard commented on content/pages/1_functionalities.md
> +
Copy paste issue?

2022-05-04 10:39 UTC, rbovard commented on content/pages/0_index_fr.md
> +GeoMapFish permet de construire des applications WebSIG de manière aisée et flexible à travers un géoportai en ligne.
```suggestion
GeoMapFish permet de construire des applications WebSIG de manière aisée et flexible à travers un géoportail en ligne.
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/1_functionalities_fr.md
> +Summary: Geomapfish est une application avec une érgonomie multi-supports et avec un large choix de fonctionnalités
```suggestion
Summary: GeoMapFish est une application avec une ergonomie multi-supports et avec un large choix de fonctionnalités 
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/2_documentation_fr.md
> +Summary: Geomapfish dispose d'une large documentation technique pour les adminisatrateurs, intégrateurs et développeurs
```suggestion
Summary: GeoMapFish dispose d'une large documentation technique pour les adminisatrateurs, intégrateurs et développeurs
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/3_gallery.md
> +Summary: Geomapfish is already functional on many geoportal
```suggestion
Summary: GeoMapFish is already functional on many geoportal
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/0_index.md
> +Summary: Geomapfish is an Open Source platform for the development of online geographic information systems (WebGIS) that provide a geoportal
```suggestion
Summary: GeoMapFish is an Open Source platform for the development of online geographic information systems (WebGIS) that provide a geoportal
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/0_index_de.md
> +Summary: Geomapfish ist eine Open-Source Plattform für die Entwicklung eines Online Geoinformationssystems (WebGIS), das ein Geoportal bereitstellt
```suggestion
Summary: GeoMapFish ist eine Open-Source Plattform für die Entwicklung eines Online Geoinformationssystems (WebGIS), das ein Geoportal bereitstellt
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/0_index_fr.md
> +Summary: Geomapfish est une plateforme Open Source pour le développement de système d'information géographique en ligne (WebSIG) qui fournit un géoportail
```suggestion
Summary: GeoMapFish est une plateforme Open Source pour le développement de système d'information géographique en ligne (WebSIG) qui fournit un géoportail
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/1_functionalities.md
> +
`GeoMapFish`

2022-05-04 10:39 UTC, rbovard commented on content/pages/1_functionalities_de.md
> +Summary: Geomapfish ist eine Anwendung mit Ergonomie für jedes digitale Medium und einer Vielzahl von Funktionen
```suggestion
Summary: GeoMapFish ist eine Anwendung mit Ergonomie für jedes digitale Medium und einer Vielzahl von Funktionen
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/2_documentation.md
> +Summary: Geomapfish has wide technical documentation for administrators, integrators and developers
```suggestion
Summary: GeoMapFish has wide technical documentation for administrators, integrators and developers
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/2_documentation_de.md
> +Summary: Geomapfish verfügt über eine umfangreiche Dokumentationstechnik für Administratoren, Integratoren und Entwickler
```suggestion
Summary: GeoMapFish verfügt über eine umfangreiche Dokumentationstechnik für Administratoren, Integratoren und Entwickler
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/3_gallery_de.md
> +Summary: Geomapfish ist bereits auf vielen Geoportalen funktionsfähig
```suggestion
Summary: GeoMapFish ist bereits auf vielen Geoportalen funktionsfähig
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/3_gallery_fr.md
> +Summary: Geomapfish est déjà fonctionel sur de nombreux géoportails
```suggestion
Summary: GeoMapFish est déjà fonctionel sur de nombreux géoportails
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/4_community.md
> +Summary: Geomapfish is part of a community with members coming from the public, private and academic sectors
```suggestion
Summary: GeoMapFish is part of a community with members coming from the public, private and academic sectors
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/4_community_de.md
> +Summary: Geomapfish ist Teil einer Community mit Mitgliedern aus dem öffentlichen, privaten und akademischen Bereich
```suggestion
Summary: GeoMapFish ist Teil einer Community mit Mitgliedern aus dem öffentlichen, privaten und akademischen Bereich
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/4_community_fr.md
> +Summary: Geomapfish fait partie d'une communauté composée de membres issus du secteur public, privé et académique
```suggestion
Summary: GeoMapFish fait partie d'une communauté composée de membres issus du secteur public, privé et académique
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/5_roadmap.md
> +Summary: Geomapfish is an Open Source platform that evolves with each version by offering many new functionalities
```suggestion
Summary: GeoMapFish is an Open Source platform that evolves with each version by offering many new functionalities
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/5_roadmap_de.md
> +Summary: Geomapfish ist eine Open-Source Plattform, die sich mit jeder Version weiterentwickelt, indem sie viele neue Funktionalitäten bietet
```suggestion
Summary: GeoMapFish ist eine Open-Source Plattform, die sich mit jeder Version weiterentwickelt, indem sie viele neue Funktionalitäten bietet
```

2022-05-04 10:39 UTC, rbovard commented on content/pages/5_roadmap_fr.md
> +Summary: Geomapfish est une plateforme Open Source qui évolue à chaque version en proposant un lot de nouvelles fonctionnalités
```suggestion
Summary: GeoMapFish est une plateforme Open Source qui évolue à chaque version en proposant un lot de nouvelles fonctionnalités 
```

2022-05-04 12:03 UTC, pfanguin commented on content/pages/1_functionalities.md
> +
Yes I think !

2022-05-04 12:04 UTC, pfanguin commented on content/pages/1_functionalities.md
> +
```suggestion
Tags: Geoportal, Open Source, GeoMapFish, GIS, Geospatial
Summary: Geomapfish is an application with a responsive ergonomics and a wide choice of functionalites
```

2022-05-04 12:14 UTC, pfanguin commented
@rbovard no I don't have a link for testing, sorry... but it's work fine (see attached image)
![image](https://user-images.githubusercontent.com/6862714/166678900-ec310710-3b1d-4808-a6f6-f535e8411e2a.png)

2022-05-04 12:19 UTC, rbovard approved these changes

2022-05-04 13:54 UTC, remyguillaume commented
Hello,

There is no problem for me with the german version... for my german level in any case :-)
Thank to you both !

2022-05-05 07:55 UTC, merged